import type { Metadata } from "next";
import { Nunito, Roboto } from "next/font/google";
import OpeningScreen from "@/components/opening-screen/opening-screen";
import { OpeningScreenProvider } from "@/components/opening-screen/opening-screen-context";
import StyleProvider from "@/providers/style-provider";
import SGlobalStyles from "@/styles/global-styles";

const nunito = Nunito({
  variable: "--font-primary",
  subsets: ["latin"],
});

const roboto = Roboto({
  weight: ["400", "500", "700"],
  variable: "--font-secondary",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="pt-Br" className={`${nunito.variable} ${roboto.variable}`}>
      <body>
        <StyleProvider>
          <SGlobalStyles />
          <OpeningScreenProvider>
            <OpeningScreen />
            {children}
          </OpeningScreenProvider>
        </StyleProvider>
      </body>
    </html>
  );
}
